#!/usr/bin/env bash
#a script that prints time 10 times else string and more conditions
n=1
while [ "$n" -le 10 ]
do
	if [ $n == 4 ]
	then
		echo "bad luck"
	elif [ $n == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((n++))
done
