#!/usr/bin/env bash
#script Bash that prints files with ls
for files in *
do 
    echo "$files" | cut -d'-' -f2
done#!/usr/bin/env bash
#script Bash that print files with ls
for files in *
do 
    echo "$files" | cut -d'-' -f2
done
